### PR TITLE
fix: improve agenda load speeds

### PR DESCRIPTION
**Pull request by DavidJFelix**
Utilize Hugo's image processing and page resources to load the images
in whatever size they originally are and compress them for the size of
the container.

This improves load times by outputting files that are the correct size
for the container. Also, since there is no text in the image, JPG was
used rather than PNG to further compression.

Compare load times on Agenda page.
Note: there are still improvements that could be made on the home page.

### CODE REVIEW

**Review by austinlparker — APPROVED** [review]

**Comment by austinlparker** [comment]
Thanks, yeah, that's a lot faster!

**Comment by DavidJFelix** [comment]
There are some other improvements I saw for the home page load times @austinlparker they're just a little harrier to get to. Thanks for the quick response. Let me know if you want any advice on how to improve the page speed there.

**Comment by austinlparker** [comment]
Sure, would love some pointers.

**Comment by DavidJFelix** [comment]
So, the about page, the home page and the header could use similar improvements, but since the images aren't defined within frontmatter in hugo, I couldn't think of a "clean" way to shrink them without shrinking the actual source image.

Here's the broad strokes of what I would try:

* I'd say PNG/SVG for the header icon, ico or PNG for the favicon, but both should be much smaller dimensions.
* The Hero probably ought to stay dimensionally as large as it currently is, but you could use JPG rather than PNG since there isn't an expectation of clean edges like a text image. Even a high quality JPG should be half the byte size.
* Your avatar image under messages should be smaller and JPG also, which is what I did on the agenda page. I did 128x128, JPG, quality 100% and it cut about 90% of the size from the original PNGS.
* Make sure if you're given the option you "interleave" the images. I think most web-focused tools  (including Hugo) do this by default, but slow-loading images won't "scan in" as obviously as they do without it.
* On the about page, handle the flavor screenshot with similar JPG compression that is used on the hero.

Specifically:

I'm not comfortable enough with hugo to know if you can resize images within templates. The way I did it on the agenda page was to load them in via the frontmatter "resources" section, which let me use the image resize functions. I wasn't sure how to do that with images that were referenced directly in the templates. If it's not possible, compressing them manually and replacing the file is the **simplest** solution. Given the time sensitivity of the site, I'd think that's a safe choice. The only thing you really give up is the ability to go back to a larger size without reverting the file changes -- which isn't a huge deal.

Hope this helps! I look forward to the stream!

**Pull request merged**
